My new branch
hackinit/ambassador pull request #1
Opened 2019-03-29 07:52 UTC by Frankie34

The env is built.
The whole service can be run in docker(with a db contain & a quill parent-container)
StartScripts will be updated with a README.md/INSTRUCTION.md

Todo List
-1. Update README.md         PRIORITY: 0
0. LOGO                                   PRIORITY: 1
1. 简历上传地址                       PRIORITY: 4
2. 车费报销方案                      PRIORITY: 3
3. 免责条款相关                      PRIORITY: 2

Other:
1. stat BUG repair(可小窗查看申请人状态,点开链接视图后未更新) PRIORITY: 5

2019-03-29 07:54 UTC, Frankie34 commented
+Todo    confirmation 界面汉化

2019-03-29 09:12 UTC, ghost reviewed
base branch确定是2018-ambassador而不是master吗？好像merge conflict比较严重……  
我晚些时候读一下代码

2019-03-29 09:24 UTC, Frankie34 commented
base master  push时候大脑宕机了

2019-03-29 09:31 UTC, shuye02 commented
不用再提PR了，  
直接push到这个branch吧，我改一下PR的base branch

2019-03-29 17:46 UTC, Frankie34 commented
Docker IMAGE:   docker pull juncheng34/hackquill:1.0

2019-03-30 05:29 UTC, ghost requested changes
两个问题  
- [ ] 代码中数据库地址是 hardcoded 的，对于docker network来说并不是一个好的习惯，会增加部署成本，最好写一个 docker-compose 文档，用其中数据库的 container 名字替代（docker 会自动解析到那个container 的地址）
- [x] 翻译中的 `参赛` 最好稍微改一下，因为校园大使并不完全等同于参赛

2019-03-30 05:29 UTC, shuye02 commented on app.js
> +var database        = process.env.DATABASE || process.env.MONGODB_URI || "mongodb://172.17.0.2:27017";
这边改成docker-compose里面的database的地址怎么样？  
因为docker network里面的地址不一定是固定的

2019-03-30 05:29 UTC, shuye02 commented on app/client/stylesheets/_branding.scss
> +$login-bg: url('https://s3.cn-north-1.amazonaws.com.cn/thehack/web-assets/img/hackinit/quill/bg.png');
这个需要改一下，今年没有用到s3，新的地址在 static.thehack.org.cn 下面，具体地址在部署之后给

2019-03-30 05:29 UTC, shuye02 commented on app/client/views/dashboard/dashboard.html
> +              确认参赛截止日期：
这边改成 `确认截止日期` 会不会好一些？（因为校园大使并不是参赛）

2019-03-30 05:29 UTC, shuye02 commented on app/client/views/dashboard/dashboard.html
> +            我确认参赛
这边同上

2019-03-30 05:29 UTC, shuye02 commented on app/client/views/dashboard/dashboard.html
> +               无法参赛，我放弃参赛资格
同上

2019-03-30 05:29 UTC, shuye02 commented on app/client/views/dashboard/dashboardCtrl.js
> +        text: "你确定自愿放弃参赛资格吗？ \n\n 一旦放弃，我们无法取消这一操作。",
同上

2019-03-30 05:29 UTC, shuye02 commented on app/client/views/dashboard/dashboardCtrl.js
> +            text: "是的，我确认放弃参赛资格",
同上

2019-03-30 06:34 UTC, Jingcheng-Pan commented on app/client/views/dashboard/dashboard.html
> +              确认参赛截止日期：
确认录用？

2019-03-30 06:35 UTC, Jingcheng-Pan commented on app/client/views/dashboard/dashboard.html
> +            我确认参赛
我确认加入 THE Hack 2019 校园大使

2019-03-30 06:37 UTC, Jingcheng-Pan commented on app/client/views/dashboard/dashboard.html
> +               无法参赛，我放弃参赛资格
无法加入，我放弃这次机会

2019-03-30 06:38 UTC, Jingcheng-Pan commented on app/client/views/dashboard/dashboardCtrl.js
> +        text: "你确定自愿放弃参赛资格吗？ \n\n 一旦放弃，我们无法取消这一操作。",
确认放弃，你确定放弃成为校园大使吗？……

2019-03-30 06:39 UTC, Jingcheng-Pan commented on app/client/views/dashboard/dashboardCtrl.js
> +            text: "是的，我确认放弃参赛资格",
是的，我确认（此次）放弃成为校园大使

2019-03-30 07:47 UTC, Frankie34 commented on app/client/views/dashboard/dashboard.html
> +              确认参赛截止日期：
已做如下修改:
校园大使确认截止日期

2019-03-30 07:47 UTC, Frankie34 commented on app/client/views/dashboard/dashboard.html
> +            我确认参赛
已修改为:
我确认加入 THE Hack 2019 校园大使

2019-03-30 07:47 UTC, Frankie34 commented on app/client/views/dashboard/dashboard.html
> +               无法参赛，我放弃参赛资格
已修改为:
无法加入 THE Hack 2019 校园大使，我放弃这次机会

2019-03-30 07:49 UTC, Frankie34 commented on app/client/views/dashboard/dashboardCtrl.js
> +        text: "你确定自愿放弃参赛资格吗？ \n\n 一旦放弃，我们无法取消这一操作。",
已修改:

title: "确认放弃",
text: "你确定放弃成为校园大使吗？？ \n\n 一旦放弃，我们无法取消这一操作。",

2019-03-30 07:49 UTC, Frankie34 commented on app/client/views/dashboard/dashboardCtrl.js
> +            text: "是的，我确认放弃参赛资格",
text: "是的，我确认放弃这次机会",

2019-03-30 08:14 UTC, Frankie34 commented on app/client/views/dashboard/dashboard.html
> +              确认参赛截止日期：
已做如下修改:
校园大使确认截止日期

2019-03-30 08:16 UTC, Frankie34 commented
将(我认为)校园大使申请确认表单中不必要的项做了注释
剩余部分做了翻译

2019-03-30 09:30 UTC, shuye02 commented
> 0. LOGO PRIORITY: 1

这个可以看一下去年的代码里面的静态文件，然后替换一下

> 1. 简历上传地址                       PRIORITY: 4

不用在代码上修改了，我们可以通过邮箱直接收2333

> 2. 车费报销方案                      PRIORITY: 3

校园大使不需要这个东西

> 3. 免责条款相关                      PRIORITY: 2

直接用英文原文就OK

2019-03-30 09:40 UTC, shuye02 commented on app.js
> +var database        = process.env.DATABASE || process.env.MONGODB_URI || "mongodb://172.17.0.2:27017";
稍等，既然有环境文件的话那就没有问题了

2019-03-30 13:44 UTC, ghost approved these changes

2019-03-30 13:44 UTC, merged